name: packaging all-in-one funcampR dock

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  funcamp-allinone:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: install_rclone
        run: |
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install curl zip unzip wget
          curl https://rclone.org/install.sh | bash
      - name: Credential
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USERNAME }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PASSWORD }}
        run: |
          rclone config create monS3 s3 env_auth true provider Minio endpoint https://minio.lab.sspcloud.fr
          rclone ls monS3:funcampr
          mkdir funcampr-gateway
          mkdir funcampr-allinone
  # Copying required statistical softwares and dependencies (R and packages, Rstudio) in portable mode
      - name: Download Initial Dock
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USERNAME }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PASSWORD }}
        run: |
          rclone copy monS3:funcampr/ressources.zip funcampr-gateway
          unzip -q funcampr-gateway/ressources.zip -d funcampr-allinone
  # Updating Grimoire Package with latest version of tutorial (datasets and .RMD) and root copy of datasets for users
      - name: Update Grimoire Package
        run: |
          wget -P funcampr-gateway https://github.com/InseeFrLab/funcamp-r-grimoire/archive/master.zip
          unzip -q funcampr-gateway/master.zip -d funcampr-gateway
          rm funcampr-gateway/master.zip
          rm -r funcampr-allinone/ressources/R/library/funcampR/data
          rm -r funcampr-allinone/ressources/R/library/funcampR/learnr
          rclone copy funcampr-gateway/funcamp-r-grimoire-master/inst funcampr-allinone/ressources/R/library/funcampR
          mkdir funcampr-allinone/data
          rclone copy funcampr-gateway/funcamp-r-grimoire-master/inst/data funcampr-allinone/data
  # Copying front-end launcher (with picts in Grimoire subfolder and hta user interface)
      - name: Download Front-end Launcher
        run: |   
          wget -P funcampr-gateway https://github.com/InseeFrLab/funcamp-r-windows-grimoire-launcher/archive/master.zip
          unzip -q funcampr-gateway/master.zip -d funcampr-gateway
          rm funcampr-gateway/master.zip
          mkdir funcampr-allinone/ressources/Grimoire
          rclone copy funcampr-gateway/funcamp-r-windows-grimoire-launcher-master/Grimoire funcampr-allinone/ressources/Grimoire
          rclone copy funcampr-gateway/funcamp-r-windows-grimoire-launcher-master/START_grimoire.hta funcampr-allinone
 # Copying icaRius game from repo
      - name: Download icaRius game
        run: |
          wget -P funcampr-gateway https://github.com/InseeFrLab/funcamp-r-icarius/releases/download/V1/data.tgz
          tar -xzf funcampr-gateway/data.tgz -C funcampr-gateway
          mkdir funcampr-allinone/ressources/solarus
          mkdir funcampr-allinone/ressources/solarus/data
          rclone copy funcampr-gateway/data funcampr-allinone/ressources/solarus/data
# Copying Solarus Game Engine
      - name: Download Solarus Game Engine
        run: |
          wget -P funcampr-gateway https://github.com/InseeFrLab/funcamp-r-windows-solarus/archive/master.zip
          unzip -q funcampr-gateway/master.zip -d funcampr-gateway
          rclone copy funcampr-gateway/funcamp-r-windows-solarus-master/solarus funcampr-allinone/ressources/solarus
  # Zipping the whole folder and pushing to S3 repo
      - name: Push On Minio
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USERNAME }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PASSWORD }}
        run: |   
          zip -q -r funcampr-gateway/funcampr-allinone.zip funcampr-allinone
          rclone copy funcampr-gateway/funcampr-allinone.zip monS3:funcampr
