name: packaging all-in-one funcampR dock

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  helloword:
    runs-on: ubuntu-latest
    container: rclone/rclone
    steps:
      - run: echo "Hello, Nono!"
      - run: export AWS_ACCESS_KEY_ID=$S3_USERNAME
      - run: export AWS_SECRET_ACCESS_KEY=$S3_PASSWORD
      - run: rclone config create monS3 s3 env_auth true provider Minio endpoint https://minio.lab.sspcloud.fr
      - run: rclone ls monS3:funcampr
