name: packaging all-in-one funcampR dock

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  helloword:
    runs-on: ubuntu-latest
    container: rclone/rclone
    steps:
      - name: Credential
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USERNAME }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PASSWORD }}
        run: |
          rclone config create monS3 s3 env_auth true provider Minio endpoint https://minio.lab.sspcloud.fr
          rclone ls monS3:funcampr
          mkdir funcampr-gateway
          mkdir funcampr-allinone
  # Copying required statistical softwares and dependencies (R and packages, Rstudio) in portable mode
      - name: Download Initial Dock
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USERNAME }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PASSWORD }}
        run: |
          rclone copy monS3:funcampr/ressources.zip funcampr-gateway
          unzip -q funcampr-gateway/ressources.zip -d funcampr-allinone
  # Copying front-end launcher (with picts in Grimoire subfolder and hta user interface)
      - name: Download Front-end Launcher
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USERNAME }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PASSWORD }}
        run: |   
          wget -P funcampr-gateway https://git.lab.sspcloud.fr/funcamp-r/funcamp-r-windows-grimoire-launcher/-/archive/master/funcamp-r-windows-grimoire-launcher-master.zip
          unzip -q funcampr-gateway/funcamp-r-windows-grimoire-launcher-master.zip -d funcampr-gateway
          mkdir funcampr-allinone/ressources/Grimoire
          rclone copy funcampr-gateway/funcamp-r-windows-grimoire-launcher-master/Grimoire funcampr-allinone/ressources/Grimoire
          rclone copy funcampr-gateway/funcamp-r-windows-grimoire-launcher-master/START_grimoire.hta funcampr-allinone
  # Copying icaRius game from repo
      - name: Download icaRius game
        run: |
          wget -P funcampr-gateway https://github.com/InseeFrLab/funcamp-r-icarius/releases/download/V1/data.tgz
          tar -xzvf funcampr-gateway/data.tgz
          mkdir funcampr-allinone/ressources/solarus/data
          rclone copy funcampr-gateway/data funcampr-allinone/ressources/solarus/data
  # Zipping the whole folder and pushing to S3 repo
      - name: Push On Minio
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_USERNAME }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_PASSWORD }}
        run: |   
          tar czf funcampr-gateway/funcampr-test.tar.gz funcampr-allinone/ressources/Grimoire
          rclone copy funcampr-gateway/funcampr-test.tar.gz monS3:funcampr

